[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mlxexample"
version = "1.0.0"
description = ""
license = { text = "Apache License (2.0)" }
dependencies = [
    "flwr[simulation]>=1.10.0,<2.0",
    "flwr-datasets[vision]>=0.0.2,<1.0.0",
    "mlx==0.10.0",
    "numpy==1.24.4",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flowerteam"

[tool.flwr.app.components]
serverapp = "mlxexample.server_app:app"
clientapp = "mlxexample.client_app:app"


[tool.flwr.app.config]
num_server_rounds = 3
num_layers = 2
hidden_dim = 32
batch_size = 256

[tool.flwr.federations]
default = "localhost"

[tool.flwr.federations.localhost]
options.num-supernodes = 10