[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pytorch-lightning"
version = "0.1.0"
description = "Federated Learning Quickstart with Flower and PyTorch Lightning"
authors = [{ name = "The Flower Authors", email = "hello@flower.ai" }]
dependencies = [
    "flwr[simulation]>=1.10.0,<2.0",
    "flwr-datasets[vision]>=0.0.3,<1.0.0",
    "pytorch-lightning<2.0.0; sys_platform == 'darwin'",
    "pytorch-lightning==1.6.0; sys_platform != 'darwin'",
    "torchvision==0.14.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flowerteam"

[tool.flwr.app.components]
serverapp = "pytorchlightning_example.server_app:app"
clientapp = "pytorchlightning_example.client_app:app"

[tool.flwr.app.config]
num_server_rounds = 3

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
