[build-system]
requires = [
    "poetry==1.1.12",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "flower_client_properties_pytorch"
version = "0.1.0"
description = "Flower client properties code example"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
flwr = "^0.19.0"
# flwr = { path = "../../", develop = true }  # Development
torch = "1.10.2"
torchvision = "0.11.3"
