[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "android_flwr_tensorflow"
version = "0.1.0"
description = "Android Example"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
# flwr = { path = "../../", develop = true }  # Development
flwr = ">=1.0,<2.0"
tensorflow-cpu = {version = ">=2.9.1,<2.11.1 || >2.11.1", markers = "(sys_platform == \"darwin\" and platform_machine == \"x86_64\") or sys_platform == \"linux\" or sys_platform == \"win32\""}
tensorflow-macos = {version = ">=2.9.1,<2.11.1 || >2.11.1", markers = "sys_platform == \"darwin\" and platform_machine == \"arm64\""}
