[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "custom-metrics"
version = "0.1.0"
description = "Federated Learning with Flower and Custom Metrics"
authors = [
	"The Flower Authors <hello@flower.dev>",
	"Gustavo Bertoli <gubertoli -at- gmail.com>"
]

[tool.poetry.dependencies]
python = "^3.8"
flwr = ">=1.0,<2.0"
scikit-learn = "^1.2.2"
tensorflow-cpu = {version = "^2.9.1, !=2.11.1", markers="platform_machine == 'x86_64'"}
tensorflow-macos = {version = "^2.9.1, !=2.11.1", markers="sys_platform == 'darwin' and platform_machine == 'arm64'"}
