---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 2 # total number of clients
num_epochs: 1 # number of local epochs
batch_size: 50
num_rounds: 200
clients_per_round: 20
learning_rate: 0.02
weight_decay: 5e-4
momentum: 0.5
lamda: 1.0 # it can be >= 0

client_resources:
  num_cpus: 4
  num_gpus: 1

server_device: cuda

fit_config:
  drop_client: false 


dataset_config:
  name: "cifar10"
  iid: false
  balance: true
  s: 0.2

model:
  _target_: fedpac.models.CIFARNet
  num_classes: 10

strategy:
  _target_: fedpac.strategy.FedPAC
  device: ${server_device}
  fraction_fit: 0.00001 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0
  evaluate_metrics_aggregation_fn:
    _target_: fedpac.strategy.metrics_average
    _partial_: true # we dont' want this function to be evaluated when instantiating the strategy, we treat it as a partial and evaluate it when the strategy actuallly calls the function (in aggregate_evaluate())


