---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 2 # total number of clients
num_epochs: 1 # number of local epochs
batch_size: 4
num_rounds: 2
clients_per_round: 2
learning_rate: 0.03
lamda: 1.0 # it can be >= 0

server_device: cuda


client_resources:
  num_cpus: 2
  num_gpus: 0


fit_config:
  drop_client: false 


dataset_config:
  name: "cifar10"
  iid: false
  balance: false
  power_law: false

model:
  _target_: fedpac.models.CIFARNet
  num_classes: 62

strategy:
  _target_: fedpac.strategy.FedPAC
  fraction_fit: 0.00001 # because we want the number of clients to sample on each roudn to be solely defined by min_fit_clients
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  min_evaluate_clients: 0
  fit_metrics_aggregation_fn: fedpac.strategy.
  evaluate_metrics_aggregation_fn:
    _target_: fedpac.strategy.weighted_average
    _partial_: true # we dont' want this function to be evaluated when instantiating the strategy, we treat it as a partial and evaluate it when the strategy actuallly calls the function (in aggregate_evaluate())


