[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-huggingface"
version = "0.1.0"
description = "Hugging Face Transformers Federated Learning Quickstart with Flower"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Kaushik Amar Das", email = "kaushik.das@iiitg.ac.in" },
]
dependencies = [
    "flwr>=1.9.0,<2.0",
    "flwr-datasets>=0.0.2,<1.0.0",
    "torch>=1.13.1,<2.0",
    "transformers>=4.30.0,<5.0",
    "evaluate>=0.4.0,<1.0",
    "datasets>=2.0.0, <3.0",
    "scikit-learn>=1.3.1, <2.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flowerteam"

[tool.flwr.app.components]
serverapp = "huggingface_example.server_app:app"
clientapp = "huggingface_example.client_app:app"

[tool.flwr.app.config]
num_server_rounds = "3"

[tool.flwr.federations]
default = "localhost"

[tool.flwr.federations.localhost]
options.num-supernodes = 2
