[project]
name = "fedgpt"
version = "1.0.0"
description = ""
license = "Apache-2.0"
authors = ["The Flower Authors <hello@flower.ai>"]

[flower.components]
serverapp = "fedgpt.server:app"
clientapp = "fedgpt.client:app"

[flower.engine]
name = "simulation" # optional

[flower.engine.simulation.super-node]
count = 10 # optional
