---
seed: 0

num_clients: 100
num_rounds: 500
clients_per_round: 20
num_epochs: 20
batch_size: 50

server_device: cuda
client_device: cuda

client_resources:
  num_cpus: 1
  num_gpus: 0.05

dataset_config:
  name: CIFAR10
  num_classes: 10
  alpha: 0.3

model:
  _target_: fedpara.models.ResNet18
  num_classes: ${dataset_config.num_classes}

hyperparams:


strategy:
  _target_: fedpara.strategy.FedPara
  algorithm: FedPara
  fraction_fit: 0.00001
  fraction_evaluate: 0.0
  min_evaluate_clients: 0
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}
  accept_failures: false

