[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "app-secaggplus"
version = "0.1.0"
description = "Example usage of the SecAggPlusWorkflow and the secaggplus_mod."
authors = ["The Flower Authors <hello@flower.ai>"]

[tool.poetry.dependencies]
python = "^3.8"
# Mandatory dependencies
flwr-nightly = { version = "1.8.0.dev20240309", extras = ["simulation"] }
