---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)


### hyper-parameters for FL pre-training ###
pre_training: true
exp_name: fedvssl_results
data_dir: /home/data1/ucf101
partition_dir: /home/data1/ucf101/annotations

# FL settings
pool_size: 2
rounds: 20

# FedVSSL strategy
strategy:
  _target_: fedvssl.strategy.FedVSSL # need to change after path modification
  mix_coeff: 0.9
  swbeta: 1
  base_work_dir: fedvssl_results
  fraction_fit: 1.0
  min_fit_clients: 2
  min_available_clients: 2
  fedavg: false

# ray config
cpus_per_client: 2
gpus_per_client: 1
include_dashboard: false


### hyper-parameters for downstream fine-tuning ###
exp_name_finetune: finetune_results
pretrained_model_path: /home/data1/round-540-weights.array.npz
