---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)


### hyper-parameters for FL pre-training ###
pre_training: false
exp_name: fedvssl_results
data_dir: fedvssl/data
partition_dir: fedvssl/data/ucf101/annotations
cfg_path_pretrain: fedvssl/conf/mmcv_conf/r3d_18_ucf101/pretraining_for_ucf.py

# FL settings
pool_size: 5
rounds: 20

# FedVSSL strategy
strategy:
  _target_: fedvssl.strategy.FedVSSL # need to change after path modification
  mix_coeff: 0.9
  swbeta: 1
  base_work_dir: fedvssl_results
  fraction_fit: 1.0
  min_fit_clients: 5
  min_available_clients: 5
  fedavg: false

# ray config
cpus_per_client: 2
gpus_per_client: 1
include_dashboard: false


### hyper-parameters for downstream fine-tuning ###
exp_name_finetune: finetune_results
cfg_path_finetune: fedvssl/CtP/configs/ctp/r3d_18_kinetics/finetune_ucf101.py
pretrained_model_path: null

# CtP file locations
dist_train_path: fedvssl/CtP/tools/dist_train.sh
dist_test_path: fedvssl/CtP/tools/dist_test.sh
test_script: fedvssl/CtP/configs/ctp/r3d_18_ucf101/finetune_ucf101_for_ucf.py

