[build-system]
requires = [
    "poetry==1.1.13",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "simulation_pytorch"
version = "0.1.0"
description = "Federated Learning Simulation with Flower and PyTorch"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.7"
flwr = { extras = ["simulation"], version = "^1.0.0" }
# flwr = { extras = ["simulation"], path = "../../", develop = true }  # Development
torch = "1.11.0"
torchvision = "0.12.0"
