---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)
#defaults:
#  - _self_
#  - override hydra/hydra_logging: disabled
#  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .

dataset:
  # dataset config
  name: mnist

model:
  # model config
  _target_: flanders.models.MnistNet

strategy:
  _target_: flanders.strategy.Flanders

server:
  _target_: flanders.server.EnhancedServer
  num_rounds: 3
  pool_size: 3
  num_malicious: 1
  warmup_rounds: 1
  sampling: 500
  history_dir: clients_params
  magnitude: 100
  attack_fn: minmax_attack

client:
  # client config