[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "quickstart-cir"
version = "0.1.0"
description = "PyTorch Federated Learning Quickstart with Flower"
authors = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
# flwr = ">=1.0,<2.0"
flwr = { path = "../../", develop = true }  # Development
torch = "1.13.1"
torchvision = "0.14.1"
tqdm = "4.65.0"
