[tool.poetry]
name = "flower_example"
version = "0.0.1"
description = "Run your ML workload federated"
authors = ["y"]

[tool.poetry.dependencies]
tensorflow-cpu = "2.3.0"
numpy = "1.18.1"
typing = "^3.7.4"
flwr = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
