[build-system]
requires = [
    "poetry==1.1.12",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "experimental_pytorch"
version = "0.1.0"
description = "PyTorch Federated Learning Quickstart with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.7.2"
#flwr = "^0.18.0"
flwr = { path = "../../", develop = true }  # Development
torch = "1.11.0"
torchvision = "0.12.0"
torchsummary = "^1.5.1"
black = "^22.3.0"
