[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "quickstart-pandas"
version = "0.1.0"
description = "Federated Analytics Quickstart with Flower and Pandas"
authors = [
    { name = "The Flower Authors", email = "hello@flower.ai" },
    { name = "Ragy Haddad", email = "ragy202@gmail.com" },
]
dependencies = [
    "flwr[simulation]>=1.10.0,<2.0",
    "flwr-datasets[vision]>=0.0.3,<1.0.0",
    "numpy==1.23.2",
    "pandas==2.0.0",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flowerteam"

[tool.flwr.app.components]
serverapp = "pandas_example.server_app:app"
clientapp = "pandas_example.client_app:app"

[tool.flwr.app.config]
num_server_rounds = 1

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 2
