[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "quickstart_huggingface"
version = "0.1.0"
description = "Hugging Face Transformers Federated Learning E2E test with Flower"
authors = [
    "The Flower Authors <hello@flower.dev>",
    "Kaushik Amar Das <kaushik.das@iiitg.ac.in>"
]

[tool.poetry.dependencies]
python = "^3.8"
flwr = { path = "../../", develop = true, extras = ["simulation"] }
torch = "^1.13.1"
transformers = "^4.30.0"
datasets = "^2.13.1"
evaluate = "^0.4.0"
scikit-learn = "^1.0"
