---
_target_: flwr.server.strategy.FedAvg
min_available_clients: ${num_clients}
fraction_fit: ${reporting_fraction}
fraction_evaluate: ${reporting_fraction}
on_fit_config_fn:
  _target_: server.get_on_fit_config
  config: ${client}