[build-system]
requires = [
    "poetry==1.1.6",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_tensorboard"
version = "0.1.0"
description = "Tensorboard Quickstart with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.2"
flwr = "^0.17.0"  # For development: { path = "../../", develop = true }
tensorflow-cpu = "==2.4.0"
