[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "federated-analytics"
version = "0.1.0"
description = "Federated Analytics with Flower"
authors = ["Ragy Haddad <ragy202@gmail.com>"]
maintainers = ["The Flower Authors <hello@flower.dev>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
flwr = ">=1.0,<2.0"
flwr-datasets = { extras = ["vision"], version = ">=0.0.2,<1.0.0" }
numpy = "1.23.2"
