---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 15 # total number of clients
num_epochs: 1 # number of local epochs
clients_per_round: 4
num_rounds: 10
learning_rate: 0.03

client_resources:

server_device: cpu

dataset:
  algo: fedavg #fedavg, fedavg(meta), fedmeta(maml), fedmeta(meta-sgd)
  path: /Users/jinsookim/PycharmProjects/fedmeta/leaf_data # Leaf Dataset path (Femnist or Shakespeare)
  support_ratio : 0.2
  batch_size : 10
  # dataset config

model:
    _target_: baselines.fedmeta.fedmeta.models.Femnist_network # model config

strategy:
  _target_: baselines.fedmeta.fedmeta.strategy.FedMeta
  # points to your strategy (either custom or exiting in Flower)
  fraction_fit: 0.00001
  fraction_evaluate: 0.00001
  min_fit_clients : ${clients_per_round}
  min_evaluate_clients : ${clients_per_round}
  min_available_clients : ${clients_per_round}
  # rest of strategy config

client:
  # client config
