---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

num_clients: 10 # total number of clients
num_epochs: 1 # number of local epochs
batch_size: 10
clients_per_round: 4
num_rounds: 10
learning_rate: 0.03

client_resources:
  num_cpus: 2
  num_gpus: 0.0

server_device: cpu

dataset:
  # dataset config

model:
    _target_: baselines.fedmeta.fedmeta.models.Femnist_network # model config

strategy:
  _target_: baselines.fedmeta.fedmeta.strategy.FedMeta
  # points to your strategy (either custom or exiting in Flower)
  fraction_fit : 0.3
  min_fit_clients: ${clients_per_round}
  min_available_clients: ${clients_per_round}

  # rest of strategy config

client:
  # client config
