---
name: flanders

strategy:
  _target_: flanders.strategy.Flanders
  to_keep: 1  # number of benign local models to keep for the aggregation (FedAvg)
  maxiter: 50 # number of iterations done by MAR