---
name: flanders

strategy:
  _target_: flanders.strategy.Flanders
  _recursive_: true
  num_clients_to_keep: 3  # number of benign local models to filter-out before the aggregation
  maxiter: 100 # number of iterations done by MAR
  alpha: 1
  beta: 1