---
dataset:
  fmnist: False

model:
  # model config

strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config

client:
  concentration: 10
  local_epochs: 1
