---
num_rounds: 10000
num_clients: 100

dataset:
  fmnist: False

model:
  # model config

strategy:
  _target_: # points to your strategy (either custom or exiting in Flower)
  # rest of strategy config

server:
  momentum: 0.9
  learning_rate: 1.0

client:
  concentration: 10
  local_epochs: 1
