[build-system]
requires = [
    "poetry==1.1.8",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_pytorch"
version = "0.1.0"
description = "PyTorch Federated Learning Quickstart with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.2"
flwr = { extras = ["simulation"], path = "../../", develop = true }
torch = "1.9.0"
torchvision = "0.10.0"
