[build-system]
requires = [
    "poetry==1.1.10",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "quickstart_pytorch"
version = "0.1.0"
description = "PyTorch: From Centralized To Federated with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.8.5"
flwr = "^0.15.0"
torch = "1.7.1"
torchvision = "0.8.2"
boto3 = "1.19.9"
smart-open = "5.2.1"
pandas = "^1.3.4"
