---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

#dataset:
exp_name: vanilla_fednova
datapath: fednova/data/
checkpoint_path: fednova/checkpoints/
results_dir: fednova/results/
num_clients: 16
num_epochs: 2
num_rounds: 100
batch_size: 32
NIID: True
alpha: 0.1
var_local_epochs: False
var_min_epochs: 2
var_max_epochs: 5
lr_scheduling: True
seed: 3491
mode: train

model:
  _target_: fednova.models.VGG

optimizer:
  _target_: fednova.models.ProxSGD
  lr: 0.05
  momentum: 0
  weight_decay: 1e-4
  gmf: 0
  mu: 0


client_resources:
  num_cpus: 1
  num_gpus: 0.125
