---
# this is the config that will be loaded as default by main.py
# Please follow the provided structure (this will ensuring all baseline follow
# a similar configuration structure and hence be easy to customise)

#dataset:
datapath: data/
num_clients: 16
num_epochs: 2
num_rounds: 100
batch_size: 32
NIID: True
alpha: 0.1
var_local_epochs: True
var_min_epochs: 2
var_max_epochs: 5
lr_scheduling: False
seed: 3491

model:
  _target_: models.VGG

optimizer:
  _target_: models.ProxSGD
  lr: 0.02
  momentum: 0.9
  weight_decay: 1e-4
  gmf: 0
  mu: 0


client_resources:
  num_cpus: 1
  num_gpus: 0.166
