[build-system]
requires = [
    "poetry==1.1.4",
]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "simulation"
version = "0.1.0"
description = "Single-Machine Federated Learning Simulation with Flower"
authors = ["The Flower Authors <enquiries@flower.dev>"]

[tool.poetry.dependencies]
python = "^3.6.1"
flwr = "==0.13.0"  # For development: { path = "../../", develop = true }
numpy = "==1.18.5"
tensorflow-cpu = "==2.4.0"

[tool.isort]
line_length = 88
indent = "    "
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_third_party = ["flwr"]
