mu = 10
num-server-rounds = 500

client-resources-num_cpus = 4
client-resources-num_gpus = 0.5

dataset-name = "uoft-cs/cifar100"
dataset-partition-by = "fine_label"

model-name = "resnet50"
model-dir = "./client_states/moon/cifar100_100c/"