num-epochs = 10
fraction-fit = 1.0
batch-size = 64
learning-rate = 0.01
mu = 0.001
temperature = 0.5
alg = "fedprox"
seed = 0
server-device = "cpu"
num-server-rounds = 500

client-resources-num_cpus = 4
client-resources-num_gpus = 0.5

dataset-name = "uoft-cs/cifar10"
dataset-partition-by = "fine_label"
dirichlet-alpha = 0.5

model-name = "resnet50"
model-output-dim = 256
model-dir = "./client_states/moon/cifar100_100c_fedprox/"