name: Baselines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-baselines:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    name: Test Baselines
    uses: ./.github/workflows/_baselines.yml

  test-baselines-fork:
    if: ${{ github.event.pull_request.head.repo.fork }}
    name: Test Baselines Fork
    uses: ./.github/workflows/_baselines-fork.yml
