name: Baselines

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

defaults:
  run:
    working-directory: baselines

jobs:
  test_baselines:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Fetch main branch
        run: |
          if [ ${{ github.event_name }} == "pull_request" ]
          then
            git fetch origin main:main
          fi
      - name: Find changed/new baselines
        id: find_changed_baselines_dirs
        run: |
          if [ ${{ github.event_name }} == "push" ]
          then
            # Push event triggered when merging to main
            change_references="HEAD..HEAD~1"
          else
            # Pull request event triggered for any commit to a pull request
            change_references="main..HEAD"
          fi
          dirs=$(git diff --dirstat=files,0 ${change_references} . | awk '{print $2}' | grep -E '^baselines/[^/]*/$' | grep -v -e '^baselines/dev' -e '^baselines/baseline_template' -e '^baselines/flwr_baselines' | sed 's/^baselines\///')
          echo "Detected changed directories: ${dirs}"
          # Save changed dirs to output of this step
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "dirs<<EOF" >> "$GITHUB_OUTPUT"
          for dir in $dirs
          do
            echo "$dir" >> "$GITHUB_OUTPUT"
          done
          echo "EOF" >> "$GITHUB_OUTPUT"
      - name: Validate changed/new baselines
        id: validate_changed_baselines_dirs
        run: |
          dirs="${{ steps.find_changed_baselines_dirs.outputs.dirs }}"
          dirs_array=()
          if [[ -n $dirs ]]; then
            while IFS= read -r line; do
              dirs_array+=("$line")
            done <<< "$dirs"
          fi
          length=${#dirs_array[@]}
          echo "The number of changed baselines is $length"
          
          if [ $length -gt 1 ]; then
          echo "The changes should only apply to a single baseline"
          exit 1
          fi
          
          if [ $length -eq 0 ]; then
          echo "The baselines were not changed - skipping the remaining steps."
          echo "baseline_changed=false" >> "$GITHUB_OUTPUT"
          exit 0
          fi
          
          echo "changed_dir=${dirs[0]}" >> "$GITHUB_OUTPUT"
          echo "baseline_changed=true" >> "$GITHUB_OUTPUT"
      - name: Set up Python
        if: steps.validate_changed_baselines_dirs.outputs.baseline_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: 3.8.15
      - name: Install build tools
        if: steps.validate_changed_baselines_dirs.outputs.baseline_changed == 'true'
        run: |
          python -m pip install -U pip==23.1.2
          python -m pip install -U setuptools==68.0.0
          python -m pip install -U poetry==1.5.1
          poetry config virtualenvs.create false
      - name: Install dependencies
        if: steps.validate_changed_baselines_dirs.outputs.baseline_changed == 'true'
        run: |
          changed_dir="${{ steps.validate_changed_baselines_dirs.outputs.changed_dir }}"
          cd "${changed_dir}"
          python -m poetry install
      - name: Test
        if: steps.validate_changed_baselines_dirs.outputs.baseline_changed == 'true'
        run: |
          dir="${{ steps.validate_changed_baselines_dirs.outputs.changed_dir }}"
          echo "Testing ${dir}"
          ./dev/test-baseline.sh $dir
      - name: Test Structure
        if: steps.validate_changed_baselines_dirs.outputs.baseline_changed == 'true'
        run: |
          dir="${{ steps.validate_changed_baselines_dirs.outputs.changed_dir }}"
          echo "Testing ${dir}"
          ./dev/test-baseline-structure.sh $dir

