name: Flower Datasets Docs

on:
  push:
    branches:
      - main
    paths:
      - "datasets/**"
  pull_request:
    branches:
      - main
    paths:
      - "datasets/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: datasets

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install dependencies (mandatory only)
        run: python -m poetry install
      - name: Build Flower Datasets docs
        run: ./dev/build-flwr-datasets-docs.sh
      - name: Deploy docs
        if: github.ref == 'refs/heads/main'
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./doc/build/html/ s3://flower.dev/docs/datasets
