name: Docker server build

on:
    # workflow_dispatch:
    #     inputs:
    #         python-version:
    #             description: "Python version"
    #             type: string
    #             required: true
    #         pip-version:
    #             description: "Pip version"
    #             type: string
    #             required: true
    #         setuptools-version:
    #             description: "Setuptools version"
    #             type: string
    #             required: true
    #         fwlr-version:
    #             description: "Flower version"
    #             type: string
    #             required: true
    push

jobs:
    build-push-image:
        name: Build server images and push them to dockerhub
        runs-on: ubuntu-22.04
        timeout-minutes: 120
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Set up QEMU
              uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
              with:
                  platforms: "arm" #"arm64"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

            - name: Login to Docker Hub
              uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - uses: ./.github/actions/bootstrap
              id: bootstrap

            - name: Build and push
              id: build
              uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
              with:
                platforms: linux/amd64 #linux/arm/v7 # linux/amd64,linux/arm64
                context: src/docker/server
                build-args: |
                    PYTHON_VERSION=${{ steps.bootstrap.outputs.python-version }}
                    PIP_VERSION=${{ steps.bootstrap.outputs.pip-version }}
                    SETUPTOOLS_VERSION=${{ steps.bootstrap.outputs.setuptools-version }}
                    FLWR_VERSION=1.6.0
                    UBUNTU_VERSION=22.04
                tags: flwr/server:1.6.0-py${{ steps.bootstrap.outputs.python-version }}-ubuntu22.04
                push: true

            - name: Summary
              run: |
                cat <<EOT >>${GITHUB_STEP_SUMMARY}
                Server image: ${{steps.build.outputs.imageid}}
                EOT
