name: Docker server build

on:
    # workflow_dispatch:
    #     inputs:
    #         python_version:
    #             description: "Python version"
    #             type: string
    #             required: true
    #             default: "3.8.0"
    #         pip_version:
    #             description: "Pip version"
    #             type: string
    #             required: true
    #             default: "23.0.1"
    #         setuptools_version:
    #             description: "Setuptools version"
    #             type: string
    #             required: true
    #             default: "69.0.2"
    #         fwlr_version:
    #             description: "Flower version"
    #             type: string
    #             required: true
    push

jobs:
    buildx:
        name: Test
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Set up QEMU
              uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
              with:
                  platforms: "arm64"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

            - name: Login to Docker Hub
              uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              id: build
              uses: docker/build-push-action@v4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
              with:
                platforms: linux/amd64,linux/arm64
                context: src/docker/server
                build-args: |
                    PYTHON_VERSION=3.8.0
                    PIP_VERSION=23.0.1
                    SETUPTOOLS_VERSION=69.0.2
                    FLWR_VERSION=1.6.0
                    UBUNTU_VERSION=22.04
                tags: flwr/server:1.6.0-py38-ubuntu22.04
                push: true

            - run: |
                cat <<EOT >>${GITHUB_STEP_SUMMARY}
                Server image: ${{steps.build.outputs.imageid}}
                EOT
