name: Docker

on:
  push:
    branches:
      - main
    # paths:
    #   -  src/docker/**
  pull_request:
    branches:
      - main
    # paths:
    #   -  src/docker/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flwr_version: [1.5.0]
    name: Test server / ${{matrix.flwr_version}}
    steps:
    - uses: actions/checkout@v3
    - name: Run server tests
      working-directory: src/docker/server
      env:
          BUILD_TARGET: server
          FLWR_VERSION: ${{ matrix.flwr_version }}
      run: ./test.sh

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flwr_version: [1.5.0]
    name: Build server / ${{matrix.flwr_version}}
    steps:
    - uses: actions/checkout@v3
    - name: Build the server image
      working-directory: src/docker/server
      env:
          BUILD_TARGET: server
          FLWR_VERSION: ${{ matrix.flwr_version }}
      run: ./build.sh
