name: Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check copyright line
        shell: bash
        run: |
          EXIT_CODE=0

          while IFS= read -r -d '' file; do
              COPYRIGHT=$(grep -h -r "copyright = " "$file")
              if [ "$COPYRIGHT" != "copyright = f\"{datetime.date.today().year} Flower Labs GmbH\"" ]; then
                  echo "::error file=$file::Wrong copyright line. Expected: copyright = f\"{datetime.date.today().year} Flower Labs GmbH\""
                  EXIT_CODE=1
              fi
          done < <(find . -path "*/doc/source/conf.py" -print0)

          exit $EXIT_CODE
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install Flower dependencies (mandatory only)
        run: python -m poetry install --extras "simulation"
      - name: Install Flower Datasets
        run: |
          cd datasets
          python -m poetry install
      - name: Build docs
        run: ./dev/build-docs.sh
      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/main' && github.repository == 'adap/flower' && !github.event.pull_request.head.repo.fork }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets. AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./doc/build/html/ s3://flower.dev/docs/framework
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./baselines/doc/build/html/ s3://flower.dev/docs/baselines
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./examples/doc/build/html/ s3://flower.dev/docs/examples
          aws s3 sync --delete --exclude ".*" --exclude "v/*" --cache-control "no-cache" ./datasets/doc/build/html/ s3://flower.dev/docs/datasets
