name: Build Tools

on:
  push:
    branches:
      - main
    paths:
      - "src/py/flwr_tool/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/py/flwr_tool/**"

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  test_tools:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry==1.3.2
          poetry config virtualenvs.create false
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15
          cache: "poetry"
          cache-dependency-path: "pyproject.toml"
      - name: Install build tools
        run: |
          python -m pip install -U pip==22.3.1
          python -m pip install -U setuptools==65.6.3
      - name: Install dependencies (mandatory + optional)
        run: |
          poetry install
      - name: Lint + Test (isort/black/mypy/pylint/pytest)
        run: ./dev/test-tool.sh
