name: Core

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLWR_TELEMETRY_ENABLED: 0

jobs:
  test-hosted-cache:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: [3.7.15, 3.7]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
