name: PR update

on:
  push:
    branches:
      - 'main'
jobs:
  autoupdate:
    runs-on: ubuntu-22.04
    steps:
      - name: Automatically update mergeable PRs
        uses: adRise/update-pr-branch@bf25036ca63c52e20013b80b876fb7752c63e169 # v0.7.1
        with:
          token: ${{ secrets.FLWRMACHINE_TOKEN }}
          base: 'main'
          required_approval_count: 1
          require_passed_checks: true
          sort: 'created'
          direction: 'desc'
